bookshop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: IWLEDSD-OW30473   
      user: ATTIDIANY
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: BOOKSHOP
      warehouse: COMPUTE_WH
      schema: STAGGING
      threads: 1